# Generated by Django 2.2.6 on 2019-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='band_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_diameter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_material',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='serial_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.FloatField(),
        ),
    ]
