# Generated by Django 2.2.6 on 2019-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191219_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='band_width',
            new_name='strap_width',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='name',
        ),
        migrations.AddField(
            model_name='watch',
            name='make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='other_materials',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='strap_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='strap_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='watchface_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(choices=[('', ''), ('M', 'Mechanical'), ('Q', 'Quartz')], default='', max_length=100),
        ),
    ]
