# Generated by Django 2.2.6 on 2019-12-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191219_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='watch',
            name='model_ref',
            field=models.CharField(default='', max_length=100),
        ),
    ]
