# Generated by Django 2.2.6 on 2019-12-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191219_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
