# Generated by Django 2.2.6 on 2019-12-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191219_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='thickness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watch',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
