# Generated by Django 2.2.6 on 2019-12-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='vatch',
            new_name='vatch_id',
        ),
    ]
