# Generated by Django 2.2.6 on 2019-12-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20191222_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='vatch',
            new_name='watch',
        ),
    ]
