# Generated by Django 2.2.6 on 2019-12-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='watch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Watch'),
            preserve_default=False,
        ),
    ]
